# Schema for the configuration files of the bookingsystem_autoecole module.
bookingsystem_autoecole.settings:
  type: config_object
  label: 'bookingsystem_autoecole settings'
  mapping:
    example:
      type: string
      label: 'Example'
