# Schema for the configuration files of the bookingsystem_autoecole module.
bookingsystem_autoecole.settings:
  type: config_object
  label: 'bookingsystem_autoecole settings'
  mapping:
    example:
      type: string
      label: 'Example'
      
field.formatter.settings.bookingsystem_autoecole_linkforcreneau:
  type: mapping
  label: LinkForCreneau formatter settings
  mapping:
    foo:
      type: string
      label: Foo
